# Generated by Django 4.0.5 on 2022-07-02 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productId', to='home.products')),
            ],
        ),
    ]
